background = 0xFF2F3541
base = 0xFF3B4352
text = 0xFFA6B8C4
alternate_base = 0xFF20242E
bright_text = 0xFF7391a5
accent = 0xFF7391a5
link_text = 0xFF7391a5
accent_secondary = 0xFF7391a5
font_family = "IBM Plex Mono"
font_family_monospace = "monospace"
font_size = 13
small_font_size = 10
rounding_large = 0
rounding_small = 0
