# theme: slate-dark
background              #2F3541
foreground              #A6B8C4
cursor                  #A6B8C4
cursor_text_color       #2F3541
selection_foreground    #2F3541
selection_background    #7391a5
active_tab_background   #20242E
active_tab_foreground   #A6B8C4
inactive_tab_background #2F3541
inactive_tab_foreground #545C69

color0  #2F3541
color8  #20242E
color1  #957A7B
color9  #957A7B
color2  #7391a5
color10 #7391a5
color3  #A6B8C4
color11 #A6B8C4
color4  #7391a5
color12 #7391a5
color5  #957A7B
color13 #957A7B
color6  #687787
color14 #687787
color7  #545C69
color15 #A6B8C4

background_opacity 0.65
