# Argvus palette
# ---
# bg         "#2F3541"
# bg-2       "#20242E"
# ui         "#3B4352"
# ui-2       "#545C69"
# ui-3       "#7391a5"
# tx-3       "#545C69"
# tx-2       "#7391a5"
# tx         "#A6B8C4"
# red-400     "#957A7B" re
# orange-400  "#8B7778" or
# yellow-400  "#A6B8C4" ye
# yellow-600  "#8B7778" ye-2
# green-400   "#7391a5" gr
# cyan-400    "#7391a5" cy
# cyan-600    "#3B4352" cy-2
# cyan-700    "#3B4352" cy-700
# cyan-900    "#20242E" cy-900
# blue-400    "#7391a5" bl
# purple-400  "#A6B8C4" pu
# magenta-400 "#957A7B" ma

[app]
overall = { bg = "#2F3541" } # bg

[mgr]
cwd = { fg = "#A6B8C4", bold = true } # tx

# Find
find_keyword = { fg = "#7391a5", reversed = true } # cy
find_position = { fg = "#7391a5", bold = true, italic = true } # cy

# Marker
marker_copied = { fg = "#7391a5", bg = "#7391a5" } # gr, gr
marker_cut = { fg = "#957A7B", bg = "#957A7B" } # re, re
marker_marked = { fg = "#3B4352", bg = "#3B4352" } # cy-700, cy-700
marker_selected = { fg = "#7391a5", bg = "#7391a5" } # cy, cy

# Count
count_copied = { fg = "#7391a5", bold = true, reversed = true } # gr
count_cut = { fg = "#957A7B", bold = true, reversed = true } # re
count_selected = { fg = "#7391a5", bold = true, reversed = true } # cy

# Border
border_symbol = "│"
border_style = { fg = "#3B4352" } # ui

[indicator]
parent = { underline = true }
current = { fg = "#A6B8C4", bg = "#3B4352" } # tx, ui
preview = { underline = true }
padding = { open = "█", close = "█" }

[tabs]
active = { fg = "#A6B8C4", bg = "#7391a5", bold = true } # tx, ui-3
inactive = { fg = "#7391a5", bg = "#3B4352" } # tx-2, ui
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

[mode]
# Normal mode
normal_main = { fg = "#A6B8C4", bg = "#7391a5", bold = true } # tx, ui-3
normal_alt = { fg = "#7391a5", bg = "#3B4352" } # tx-2, ui

# Select mode
select_main = { fg = "#2F3541", bg = "#7391a5", bold = true } # bg, cy
select_alt = { fg = "#7391a5", bg = "#20242E" } # cy, cy-900

# Unset mode
unset_main = { fg = "#2F3541", bg = "#7391a5", bold = true } # bg, cy
unset_alt = { fg = "#7391a5", bg = "#20242E" } # cy, cy-900

[status]
overall = { fg = "#A6B8C4" } # tx

# Permissions
perm_type = { fg = "#7391a5" } # bl
perm_read = { fg = "#A6B8C4" } # ye
perm_write = { fg = "#957A7B" } # re
perm_exec = { fg = "#7391a5" } # gr
perm_sep = { fg = "#7391a5" } # tx-2

# Progress
progress_label = { fg = "#2F3541" } # bg
progress_normal = { fg = "#7391a5", bg = "#3B4352" } # cy, cy-700
progress_error = { bg = "#957A7B" } # re

[which]
cols = 3
mask = { bg = "#20242E" } # bg-2
cand = { fg = "#7391a5", bold = true } # cy
rest = { fg = "#7391a5", italic = true } # cy
desc = { fg = "#545C69" } # tx-3
separator = " "
separator_style = { }

[confirm]
border = { fg = "#7391a5" } # ui-3
title = { fg = "#545C69", bold = true } # tx-3
body = { fg = "#A6B8C4", bold = true } # tx
list = { fg = "#A6B8C4" } # tx
btn_yes = { fg = "#A6B8C4", bg = "#7391a5", bold = true } # tx, ui-3
btn_no = { fg = "#7391a5", bg = "#3B4352" } # tx-2, ui

[spot]
border = { fg = "#7391a5" } # ui-3
title = { fg = "#545C69", bold = true } # tx-3
tbl_col = { fg = "#7391a5" } # tx-2
tbl_cell = { fg = "#A6B8C4", bg = "#3B4352" } # tx, ui

[notify]
# Notification title
title_info = { fg = "#7391a5" } # bl
title_warn = { fg = "#8B7778" } # or
title_error = { fg = "#957A7B" } # re

[pick]
border = { fg = "#7391a5", bold = true } # ui-3
active = { fg = "#A6B8C4" } # tx
inactive = { fg = "#7391a5" } # tx-2

[input]
border = { fg = "#7391a5" } # ui-3
title = { fg = "#545C69", bold = true } # tx-3
value = { fg = "#A6B8C4" } # tx
selected = { bg = "#20242E" } # bg-2

[cmp]
border = { fg = "#7391a5", bold = true } # ui-3
active = { fg = "#A6B8C4", bg = "#3B4352" } # tx, ui
inactive = { fg = "#7391a5" } # tx-2

[tasks]
border = { fg = "#7391a5" } # ui-3
title = { fg = "#545C69", bold = true } # tx-3
hovered = { fg = "#A6B8C4", bg = "#3B4352" } # tx, ui

[help]
on = { fg = "#7391a5" } # bl
run = { fg = "#7391a5" } # cy
desc = { fg = "#545C69", italic = true } # tx-3
hovered = { bg = "#3B4352" } # ui
footer = { fg = "#2F3541", bg = "#7391a5", bold = true } # bg, cy

[filetype]
rules = [
  # Empty files
  { mime = "inode/empty", fg = "#545C69" }, # tx-3

  # Special files
  { url = "*", is = "orphan", fg = "#545C69" }, # tx-3
  { url = "*/", is = "orphan", fg = "#545C69" }, # tx-3
  { url = "*", is = "link", fg = "#7391a5" }, # cy
  { url = "*/", is = "link", fg = "#7391a5" }, # cy
  { url = "*", is = "block", fg = "#A6B8C4" }, # tx
  { url = "*", is = "char", fg = "#A6B8C4" }, # tx
  { url = "*", is = "fifo", fg = "#957A7B" }, # ma
  { url = "*", is = "sock", fg = "#957A7B" }, # ma
  { url = "*", is = "sticky", fg = "#A6B8C4" }, # tx
  { url = "*", is = "dummy", fg = "#545C69" }, # tx-3

  # Fallback
  { url = "*/", fg = "#A6B8C4" }, # tx
  { url = "*", is = "exec", fg = "#7391a5" }, # gr
  { url = "*", fg = "#7391a5" } # tx-2
]

[icon]
dirs = [
  { name = ".config", text = "", fg = "#7391a5" }, # cy
  { name = ".git", text = "", fg = "#7391a5" }, # cy
  { name = ".github", text = "", fg = "#7391a5" }, # cy
  { name = ".npm", text = "", fg = "#7391a5" }, # cy
  { name = "Desktop", text = "", fg = "#7391a5" }, # cy
  { name = "Development", text = "", fg = "#7391a5" }, # cy
  { name = "Documents", text = "", fg = "#7391a5" }, # cy
  { name = "Downloads", text = "", fg = "#7391a5" }, # cy
  { name = "Library", text = "", fg = "#7391a5" }, # cy
  { name = "Movies", text = "", fg = "#7391a5" }, # cy
  { name = "Music", text = "", fg = "#7391a5" }, # cy
  { name = "Pictures", text = "", fg = "#7391a5" }, # cy
  { name = "Public", text = "", fg = "#7391a5" }, # cy
  { name = "Videos", text = "", fg = "#7391a5" } # cy
]
conds = [
  # Special files
  { if = "orphan", text = "", fg = "#545C69" }, # tx-3
  { if = "link", text = "", fg = "#7391a5" }, # cy
  { if = "block", text = "", fg = "#A6B8C4" }, # tx
  { if = "char", text = "", fg = "#A6B8C4" }, # tx
  { if = "fifo", text = "", fg = "#957A7B" }, # ma
  { if = "sock", text = "", fg = "#957A7B" }, # ma
  { if = "sticky", text = "", fg = "#A6B8C4" }, # tx
  { if = "dummy", text = "", fg = "#545C69" }, # tx-3

  # Fallback
  { if = "dir", text = "", fg = "#7391a5" }, # cy
  { if = "exec", text = "", fg = "#7391a5" }, # gr
  { if = "!dir", text = "", fg = "#7391a5" } # tx-2
]